### ISSUE TITLE
Some Games To Add

### ISSUE THREAD

**Issue by bgiesing** [Da532/NS-RPC#3]
- [ ] Ace Attorney Trilogy
- [ ] All of the SEGA AGES titles (Sonic, Out Run, etc)
- [ ] All the Final Fantasy remasters/ports
- [ ] All the Resident Evil ports
- [ ] Baba Is You
- [ ] Bloodstained: Ritual of the Night
- [ ] Both Dragon Quest Builders games
- [ ] Brawlhalla
- [ ] CATAN
- [ ] CELESTE
- [ ] Crypt of the Necrodancer (you have the Zelda spin off but not the original)
- [ ] Darkest Dungeon
- [ ] Dead Cells
- [ ] DELTARUNE Chapter 1
- [ ] Devil May Cry
- [ ] Fallout Shelter
- [ ] Famicom Online (You have the US NES version but both can be used in all regions and have different games so it makes sense to have both separately)
- [ ] Hellblade
- [ ] Hollow Knight
- [ ] Just Shapes & Beats
- [ ] KAMIKO
- [ ] Katana ZERO
- [ ] Mario & Rabbids: Kingdom Battle
- [ ] MegaMan 11
- [ ] My Time at Portia
- [ ] Pokemon Quest
- [ ] Puyo Puyo Champions
- [ ] Puyo Puyo Tetris
- [ ] Shovel Knight: Treasure Trove
- [ ] Slay The Spire
- [ ] Super Neptunia RPG
- [ ] Team Sonic Racing
- [ ] Terraria
- [ ] UNDERTALE
- [ ] UNO
- [ ] Unravel Two

**Comment by Da532** [comment]
I choose to keep the library the way it is because I aim to hit the popular games. The current system would be overwhelming with that many options but I plan to make a better selection system soon. I'll add important entries from that list next update or potentially when I set the games to be grabbed from the web so updates won't be needed so frequently.
